// OS PARAMETRO DEVEM SER TIPADOS E TAMBÉM O RETORNO DA FUNÇÃO
// MAS CASO NÃO TIPE O RETORNO DA F, O TS POSSUI INTELIGÊNCIA PARA AUTO TIPAR O RETORNO

const soma = (X: number, Y: number): number => {
  return X + Y
}

// VALUE É DO TIPO NUMBER POR CAUSA DO RETORNO DA FUNÇÃO
const value = soma(10, 10)