// OS PARAMETROS DEVEM SER TIPADOS
// MAS CASO NÃO TIPE O RETORNO DA F, O TS POSSUI INTELIGÊNCIA PARA AUTO TIPAR O RETORNO

const soma = (X: number, Y: number): number => {
  return X + Y
}

// VALUE É DO TIPO NUMBER POR CAUSA DO RETORNO DA FUNÇÃO
const value = soma(10, 10)